import 'package:flutter/material.dart';import 'package:flutter_riverpod/flutter_riverpod.dart';import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';import '../../../core/constants/app_text_styles.dart';import '../domain/settings_provider.dart';

class SettingsScreen extends ConsumerWidget{const SettingsScreen({super.key});
  @override Widget build(BuildContext c,WidgetRef ref){final s=ref.watch(settingsProvider);final l=s.locale=='zh';
    return Scaffold(appBar:AppBar(title:Text(l?'设置':'Settings')),body:ListView(padding:const EdgeInsets.symmetric(vertical:8),children:[
      _sec(l?'外观':'Appearance'),SwitchListTile(title:Text(l?'深色模式':'Dark Mode'),subtitle:Text(l?'切换深色/浅色主题':'Toggle dark/light'),secondary:const Icon(Icons.dark_mode_outlined),value:s.isDarkMode,onChanged:(v)=>ref.read(settingsProvider.notifier).toggleDarkMode()),ListTile(leading:const Icon(Icons.language),title:Text(l?'语言':'Language'),subtitle:Text(s.locale=='zh'?'中文':'English'),trailing:SegmentedButton<String>(segments:const[ButtonSegment(value:'zh',label:Text('中文')),ButtonSegment(value:'en',label:Text('EN'))],selected:{s.locale},onSelectionChanged:(v){ref.read(settingsProvider.notifier).setLocale(v.first);},style:ButtonStyle(visualDensity:VisualDensity.compact,tapTargetSize:MaterialTapTargetSize.shrinkWrap))),const Divider(height:1),
      _sec(l?'课表设置':'Schedule'),ListTile(leading:const Icon(Icons.grid_view_outlined),title:Text(l?'每日显示节数':'Sections per day'),subtitle:Text(l?'设置课表网格行数':'Grid rows'),trailing:DropdownButton<int>(value:s.maxSectionsPerDay,underline:const SizedBox(),items:[8,10,12,14].map((n)=>DropdownMenuItem(value:n,child:Text('$n'))).toList(),onChanged:(v){if(v!=null)ref.read(settingsProvider.notifier).setMaxSections(v);})),ListTile(leading:const Icon(Icons.access_time),title:Text(l?'每节上课时间':'Class times'),subtitle:Text('${s.sectionTimes.length} ${l?'节课':'slots'}'),trailing:const Icon(Icons.chevron_right),onTap:()=>_showTimes(c,ref,s.sectionTimes,l)),const Divider(height:1),
      SwitchListTile(title:Text(l?'显示周末':'Show weekends'),subtitle:Text(l?'是否在课表中显示周六和周日':'Show sat/sun'),secondary:const Icon(Icons.weekend_outlined),value:s.showWeekends,onChanged:(v)=>ref.read(settingsProvider.notifier).toggleWeekends()),const Divider(height:1),
      _sec(l?'通知':'Notifications'),SwitchListTile(title:Text(l?'上课提醒':'Class reminder'),subtitle:Text(l?'上课前通过通知提醒':'Notify before class'),secondary:const Icon(Icons.notifications_outlined),value:s.enableNotifications,onChanged:(v)=>ref.read(settingsProvider.notifier).toggleNotifications()),if(s.enableNotifications)ListTile(leading:const Icon(Icons.timer_outlined),title:Text(l?'提前提醒时间':'Advance time'),subtitle:Text(l?'上课前几分钟提醒':'Minutes before'),trailing:DropdownButton<int>(value:s.notificationMinutes,underline:const SizedBox(),items:[5,10,15,20,30].map((n)=>DropdownMenuItem(value:n,child:Text('$n ${l?'分钟':'min'}'))).toList(),onChanged:(v){if(v!=null)ref.read(settingsProvider.notifier).setNotificationMinutes(v);})),const Divider(height:1),
      _sec(l?'数据':'Data'),ListTile(leading:const Icon(Icons.delete_sweep_outlined,color:AppColors.error),title:Text(l?'清除所有课表数据':'Clear all data',style:const TextStyle(color:AppColors.error)),subtitle:Text(l?'删除所有已导入的课程':'Delete all courses'),onTap:()=>_showClear(c,ref,l)),const Divider(height:1),
      _sec(l?'关于':'About'),const ListTile(leading:Icon(Icons.info_outline),title:Text('版本'),subtitle:Text('1.0.0')),ListTile(leading:const Icon(Icons.system_update),title:Text(l?'检查更新':'Check Update'),subtitle:Text(l?'检查并下载最新版本':'Check & download latest'),trailing:const Icon(Icons.chevron_right),onTap:()=>c.pushNamed('update')),
    ]));}
  Widget _sec(String t)=>Padding(padding:const EdgeInsets.fromLTRB(16,20,16,8),child:Text(t,style:AppTextStyles.caption.copyWith(fontWeight:FontWeight.w600,color:AppColors.primary,letterSpacing:0.5)));
  void _showTimes(BuildContext c,WidgetRef ref,Map<int,String> times,bool l){showModalBottomSheet(context:c,isScrollControlled:true,useSafeArea:true,shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(20))),builder:(ctx)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(l?'设置每节上课时间':'Set class times',style:AppTextStyles.heading2),const SizedBox(height:4),Text(l?'格式: HH:mm':'Format: HH:mm',style:AppTextStyles.caption),const SizedBox(height:16),SizedBox(height:MediaQuery.of(c).size.height*0.5,child:ListView(children:times.entries.map((e)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(children:[SizedBox(width:50,child:Text(l?'第${e.key}节':'No.${e.key}',style:AppTextStyles.body)),const SizedBox(width:12),Expanded(child:TextField(controller:TextEditingController(text:e.value),decoration:const InputDecoration(hintText:'HH:mm',border:OutlineInputBorder(),isDense:true),onChanged:(v){ref.read(settingsProvider.notifier).setSectionTime(e.key,v);}))]))).toList())),const SizedBox(height:16),FilledButton(onPressed:()=>Navigator.pop(c),child:Text(l?'完成':'Done'))])));}
  void _showClear(BuildContext c,WidgetRef ref,bool l){showDialog(context:c,builder:(ctx)=>AlertDialog(title:Text(l?'清除数据':'Clear data'),content:Text(l?'确定要删除所有课表数据吗？此操作不可撤销。':'Delete all schedule data? This cannot be undone.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:Text(l?'取消':'Cancel')),FilledButton(onPressed:(){ref.read(settingsProvider.notifier).clearAllData();Navigator.pop(c);},style:FilledButton.styleFrom(backgroundColor:AppColors.error),child:Text(l?'全部删除':'Delete all'))]));}
}
